### ISSUE TITLE
Resizing

### ISSUE THREAD

**Issue by bobSmith121** [Legacy-Scripts/LGF_Hud_V2#3]
if you use resizable the hud icons will overlay the map.

**Comment by ENT510** [comment]
you can provide a photo pls?

**Comment by bobSmith121** [comment]
![image](https://github.com/user-attachments/assets/757ee179-8f65-436d-b26d-7f2c188a4f3b)

**Comment by ENT510** [comment]
you can simply make the map from the file functions more large
